[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/railway.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8081"
NODE_ENV = "production"
